"""empty message

Revision ID: 5acf95d8a6dc
Revises: 
Create Date: 2018-10-18 13:56:03.559843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acf95d8a6dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('version',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('application', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application'], ['application.id'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version')
    op.drop_table('application')
    # ### end Alembic commands ###
